#display line ids
line_1: ln1_?
line_2: ln2_?
#sensor light labels
status_A: READY
status_B: ARMED
status_C: TROUBLE
status_D: AC

#sensor associated binary_sensor id's
#Enter the type_id of the binary status field.  
#Replace the partition number with ? as it will be used to substitute for the active partition
sensor_A: rdy_?
sensor_B: arm_?
sensor_C: tr
sensor_D: ac


#cmd button labels
button_A: STAY
button_B: AWAY
button_C: NIGHT
button_F: '<'
button_G: '>'

#button key cmds
cmd_A: S
cmd_B: W
cmd_C: N
cmd_F: '<'
cmd_G: '>'


#keypad number secondary function labels
text_1: BYPASS
text_2: SERV
text_3: ALARMS
text_4: CHIME
text_5: CODES
text_6: FUNC
text_7: OUTP
text_8: PROG
text_9: NIGHT
text_star: SELECT
text_pound: ENTER
text_0: ''

#beep binary sensor. not implemented yet
beep: bp_?

#keypad display control options
view_pad: true
view_display: true
view_status: true
view_status2: false
view_bottom: true
button_left: false
vibration_duration: 5

#status icon configuration for sensors
status_A_off_icon: mdi:circle-off-outline
status_A_on_icon: mdi:check-circle
status_A_color: green
status_C_on_icon: mdi:alert
status_C_off_icon: mdi:triangle-outline
status_C_color: orange
status_B_on_icon: mdi:shield-lock
status_B_off_icon: mdi:shield-off-outline
status_B_color: red
status_D_on_icon: mdi:power-plug
status_D_off_icon: mdi:power-plug-off-outline
status_D_color: green

#optional styling and colors for keypad if needed. 
style:
  --hovercolordark: "#303030"
  --focuscolordark: "#404040"
  --activecolordark: "#505050"
  --sensorlabelcolordark: "#ff9800"
  --buttonbgcolordark: "#252525"
  --buttontextcolordark: "#03a9f4"
  --lcdbgcolordark: "#888"
  --lcdtextcolordark: "#000"
  --bordercolordark: "#555"
  --sensoroffcolordark: "#333"

  --hovercolorlight: "#eee"
  --focuscolorlight: "#ddd"
  --activecolorlight: "#999"
  --sensorlabelcolorlight: "#222"
  --buttonbgcolorlight: "#f5f5f5"
  --buttontextcolorlight: "#03a9f4"
  --lcdbgcolorlight: "#ccc"
  --lcdtextcolorlight: "#222"
  --bordercolorlight: "#898e94"
  --sensoroffcolorlight: "#bbb"


