
status_A: ARMED
status_B: READY
status_C: TROUBLE
status_D: CHIME
status_E: ''
status_F: ''
status_G: ''
status_H: ''
sensor_A: arm_?
sensor_B: rdy_?
sensor_C: tr
sensor_D: chm_?
button_A: ''
button_B: ''
button_C: ''
button_D: ''
button_F: ''
button_G: ''
button_E: ''
button_H: ''
cmd_A: ''
cmd_B: ''
cmd_C: ''
cmd_D: ''
cmd_E: ''
cmd_H: ''
cmd_F: ''
cmd_G: ''
text_1: OFF
text_2: AWAY
text_3: STAY
text_4: MAX
text_5: TEST
text_6: BYPASS
text_7: INSTANT
text_8: CODE
text_9: CHIME
text_star: READY
text_pound: ''
text_0: ''
beep: bp_?
view_pad: true
view_display: true
view_status: true
view_status_2: false
view_bottom: true
button_left: false
partitions: 1
default_partition: 1

