#display line ids
line_1: ln1_?
line_2: ln2_?
#sensor light labels
status_A: ARMED
status_B: READY
status_C: TROUBLE
status_D: CHIME
status_E: 'AWAY'
status_F: 'STAY'
status_G: 'INST'
status_H: 'AC'
#sensor associated binary_sensor id's
#Enter the type_id of the binary status field 
#Replace the partition number with ? as it will be used to substitute for the active partition
sensor_A: arm_? 
sensor_B: rdy_?
sensor_C: trbl_?
sensor_D: chm_?
sensor_E: arma_?
sensor_F: arms_?
sensor_G: armi_?
sensor_H: ac

#cmd button labels
button_A: 'AWAY'
button_B: 'STAY'
button_C: 'NIGHT'
button_D: 'INST'
button_E: 'BYPAS'
button_F: 'BPLST'
button_G: ''
button_H: ''
#button key cmds
cmd_A: 'A'
cmd_B: 'S'
cmd_C: 'N'
cmd_D: 'I'
cmd_E: 'B'
cmd_F: 'Y'
cmd_G: ''
cmd_H: ''


#keypad number secondary function labels
text_1: OFF
text_2: AWAY
text_3: STAY
text_4: MAX
text_5: TEST
text_6: BYPASS
text_7: INSTANT
text_8: CODE
text_9: CHIME
text_star: READY
text_pound: ''
text_0: ''

#beep binary sensor. not implemented yet
beep: bp_?

#keypad display control options
view_pad: true
view_display: true
view_status: true
view_status2: false
view_bottom: true
button_left: false

