#display line ids
line_1: ln1_?
line_2: ln2_?
#sensor light labels
status_A: ARMED
status_B: READY
status_C: TROUBLE
status_D: 'AC'
status_E: CHIME

#sensor associated binary_sensor id's
#Enter the type_id of the binary status field 
#Replace the partition number with ? as it will be used to substitute for the active partition
sensor_A: arm_? 
sensor_B: rdy_?
sensor_C: trbl_?
sensor_D: ac
sensor_E: chm_?

#cmd button labels
button_A: 'AWAY'
button_B: 'STAY'
button_C: 'NIGHT'
button_D: 'INST'
button_E: 'BYPAS'
button_F: 'BPLST'
button_G: ''
button_H: ''
#button key cmds
cmd_A: 'A'
cmd_B: 'S'
cmd_C: 'N'
cmd_D: 'I'
cmd_E: 'B'
cmd_F: 'Y'
cmd_G: ''
cmd_H: ''

#keypad number secondary function labels
text_1: OFF
text_2: AWAY
text_3: STAY
text_4: MAX
text_5: TEST
text_6: BYPASS
text_7: INSTANT
text_8: CODE
text_9: CHIME
text_star: READY
text_pound: ''
text_0: ''

#beep binary sensor. not implemented yet
beep: bp_?

#keypad display control options
view_pad: true
view_display: true
view_status: true
view_status2: false
view_bottom: false
button_left: false
vibration_duration: 5

#sensor on/off icons
status_A_on_icon: mdi:shield-lock
status_A_off_icon: mdi:shield-off-outline
status_A_color: red
status_B_off_icon: mdi:circle-off-outline
status_B_on_icon: mdi:check-circle
status_B_color: green
status_C_on_icon: mdi:alert
status_C_off_icon: mdi:triangle-outline
status_C_color: orange
status_E_on_icon: mdi:power-plug
status_E_off_icon: mdi:power-plug-off-outline
status_E_color: green

#optional styling and keypad colors
style:
  --hovercolordark: "#303030"
  --focuscolordark: "#404040"
  --activecolordark: "#505050"
  --sensorlabelcolordark: "#ff9800"
  --buttonbgcolordark: "#252525"
  --buttontextcolordark: "#03a9f4"
  --lcdbgcolordark: "#888"
  --lcdtextcolordark: "#000"
  --bordercolordark: "#555"
  --sensoroffcolordark: "#333"

  --hovercolorlight: "#eee"
  --focuscolorlight: "#ddd"
  --activecolorlight: "#999"
  --sensorlabelcolorlight: "#222"
  --buttonbgcolorlight: "#f5f5f5"
  --buttontextcolorlight: "#03a9f4"
  --lcdbgcolorlight: "#ccc"
  --lcdtextcolorlight: "#222"
  --bordercolorlight: "#898e94"
  --sensoroffcolorlight: "#bbb"

