
status_A: ARMED
status_B: READY
status_C: TROUBLE
status_D: CHIME
status_E: ''
status_F: ''
status_G: ''
status_H: ''
sensor_A: arm_?
sensor_B: rdy_?
sensor_C: trbl_?
sensor_D: chm_?
sensor_E: ''
sensor_F: ''
sensor_G: ''
sensor_H: ''
button_A: 'AWAY'
button_B: 'STAY'
button_C: 'NIGHT'
button_D: 'INSTANT'
button_E: 'BYPASS'
button_F: 'BP LIST'
button_G: ''
button_H: ''
cmd_A: 'A'
cmd_B: 'S'
cmd_C: 'N'
cmd_D: 'I'
cmd_E: 'B'
cmd_H: 'Y'
cmd_F: ''
cmd_G: ''
text_1: OFF
text_2: AWAY
text_3: STAY
text_4: MAX
text_5: TEST
text_6: BYPASS
text_7: INSTANT
text_8: CODE
text_9: CHIME
text_star: READY
text_pound: ''
text_0: ''
beep: bp_?
view_pad: true
view_display: true
view_status: true
view_status_2: false
view_bottom: true
button_left: false
partitions: 1
default_partition: 1

