#display line ids
line_1: ln1_?
line_2: ln2_?

#sensor associated binary_sensor id's
#Enter the type_id of the binary status field.  
#Replace the partition number with ? as it will be used to substitute for the active partition
sensor_ready: rdy_?
sensor_armed: arm_?
sensor_trouble: tr
sensor_ac: ac

#button key cmds
cmd_stay: S
cmd_away: W
cmd_chime: C
cmd_reset: R
cmd_exit: X
cmd_fire: F
cmd_alert: A
cmd_panic: P


#keypad number secondary function labels
text_1: BYPASS
text_2: SERV
text_3: ALARMS
text_4: CHIME
text_5: CODES
text_6: FUNC
text_7: OUTP
text_8: PROG
text_9: NIGHT
text_star: SELECT
text_pound: ENTER
text_0: ''

#beep binary sensor. not implemented yet
beep: bp_?

vibration_duration: 5

#optional styling and colors for keypad if needed. 
style:
    --maingrpbgcolordark: "#111"
    --btngrpbgcolordark: "#111"
    --buttonbgcolordark: "#252525"
    --buttontextcolordark: "#03a9f4"
    --lcdbgcolordark: "#859c99"
    --lcdtextcolordark: "#222"
    --sensoroffdark: "#303030"
    --bordercolordark: "#333"
    --hovercolordark: "#444"
    --activecolordark: "#555"
    --focuscolordark: "#454545"

    --maingrpbgcolorlight: "#ddd"
    --btngrpbgcolorlight:  "whitesmoke"
    --buttonbgcolorlight: "#d9dcdf"
    --buttontextcolorlight: "#222"
    --lcdbgcolorlight: "#859c99"
    --lcdtextcolorlight: "#222"
    --sensorofflight: "#ccc"
    --bordercolorlight: "#bbb"
    --hovercolorlight: "#c0c0c0"
    --activecolorlight: "#d0d0d0"
    --focuscolorlight: "#c5c5c5"




